source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-datatables-rails', git: 'git://github.com/rweng/jquery-datatables-rails.git'
gem 'jquery-ui-rails'
gem 'jquery-cookie-rails'
gem 'jbuilder', '~> 1.2'
gem 'yui-compressor'
gem 'twitter-bootswatch-rails', '~> 3.0.3'
gem 'twitter-bootswatch-rails-helpers'
gem 'bootstrap-tour-rails'
gem 'bootstrap-datepicker-rails'
gem 'therubyracer'
gem 'less-rails'
gem 'font-awesome-sass'
gem 'protected_attributes'
gem 'devise'
gem 'omniauth'
gem 'omniauth-vkontakte'
gem 'omniauth-facebook'

group :development, :test do
  gem 'sqlite3'
  gem 'webrick'
  gem 'capistrano'
  gem 'debugger'
  gem 'rvm-capistrano'
  gem 'rspec-rails'
  gem 'capybara'
end
group :production do
  gem 'pg'
  gem 'unicorn'
end
